### ISSUE TITLE
pending ops: replacement op must increase maxFeePerGas and MaxPriorityFeePerGas by >= 10%

### ISSUE THREAD

**Issue by weiihann** [stackup-wallet/erc-4337-examples#25]
I'm running my Geth node and stackup bundler on my machine. When I run `yarn run simpleAccount transfer --to <address> --amount 0.01`. I got the following error:

```
  error: Error: pending ops: replacement op must increase maxFeePerGas and MaxPriorityFeePerGas by >= 10%
      at getResult (/server2/weihan/erc-4337-examples/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:142:28)
      at processJsonFunc (/server2/weihan/erc-4337-examples/node_modules/@ethersproject/web/src.ts/index.ts:383:22)
      at /server2/weihan/erc-4337-examples/node_modules/@ethersproject/web/src.ts/index.ts:320:42
      at step (/server2/weihan/erc-4337-examples/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/server2/weihan/erc-4337-examples/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/server2/weihan/erc-4337-examples/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: -32602,
    data: 'pending ops: replacement op must increase maxFeePerGas and MaxPriorityFeePerGas by >= 10%'
  },
  requestBody: '{"method":"eth_sendUserOperation","params":[{"sender":"0xFC901229E04ca3fB830a5658A09807a7D5a012AF","nonce":"0x0","initCode":"0x71d63edcda95c61d6235552b5bc74e32d8e2527b5fbfb9cf0000000000000000000000009c85856d30cff8847939adbae5bddf3f7c549f960000000000000000000000000000000000000000000000000000000000000000","callData":"0xb61d27f6000000000000000000000000519eaeb4fd8986e2bc8a23741f2bf84fff3b2857000000000000000000000000000000000000000000000000002386f26fc1000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000","callGasLimit":"0x5580","verificationGasLimit":"0x65139","maxFeePerGas":"0x51b5f0c4a","maxPriorityFeePerGas":"0x285c28","paymasterAndData":"0x","preVerificationGas":"0xaf9c","signature":"0xadc7c317397fba318fe075654586d4cb90ff1de3b92dd9ce271bca0f8403b571159dbc6924c3b50b40862369ff9426117d7930053669020dca1afec6dd500e7e1c"},"0x0576a174D229E3cFA37253523E645A78A0C91B57"],"id":43,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'http://localhost:4337'
}
```

Here's the Geth node command:
```
./go-ethereum/build/bin/geth --goerli --datadir /server2/weihan/ethereum/execution/datadir  --http --http.api="eth,web3,net,debug" --http.vhosts="*" --http.corsdomain "*" --authrpc.jwtsecret=/opt/jwtsecret --authrpc.vhosts="*"
```

May I ask if there's any solution to this issue?

**Comment by weiihann** [comment]
Found the solution:

It's because I didn't fund the bundler address.
